version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    volumes:
      - redis-data:/data
    container_name: "redis"
  app:
    build:
      context: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis
    env_file:
      - .env
    container_name: "url-shortener"
volumes:
  redis-data: